Added checks for GPG_AGENT_INFO.
If the environment variable GPG_AGENT_INFO is not set, try to find the
GPG agent information for the currently running reprepro_watch process.

If that is not found, then exit out with non-zero status, because it's
not possible to continue.

diff --git a/scripts/preset_passphrase b/scripts/preset_passphrase
--- a/scripts/preset_passphrase
+++ b/scripts/preset_passphrase
@@ -6,6 +6,16 @@ KEY=$1
 
 [ -z "${KEY}" ] && echo "${SCRIPT_NAME} <PGP Key>" 1>&2 && exit 1
 
+agent_info=/var/run/reprepro_watch/gpg-agent.env
+if [ -z "${GPG_AGENT_INFO}" ] && [ -e "${agent_info}" ]; then
+    export $(cat ${agent_info})
+fi;
+
+if [ -z "${GPG_AGENT_INFO}" ]; then
+    echo "GPG_AGENT_INFO environment variable is not set, cannot continue" 1>&2
+    exit 1
+fi;
+
 # get original stty setting
 stty_orig=`stty -g`
 
